export enum Stack {
  프론트엔드 = 'FRONTEND',
  백엔드 = 'BACKEND',
  모바일 = 'ANDROID_IOS',
}

export enum QuestionStatus {
  DONE = 'DONE',
  TODO = 'TODO',
}

export enum CSCategory {
  DATA_STRUCTURES_ALGORITHMS = 'DATA_STRUCTURES_ALGORITHMS',
  OPERATING_SYSTEMS = 'OPERATING_SYSTEMS',
  NETWORKING = 'NETWORKING',
  DATABASES = 'DATABASES',
  SECURITY = 'SECURITY',
  LANGUAGE_AND_DEVELOPMENT_PRINCIPLES = 'LANGUAGE_AND_DEVELOPMENT_PRINCIPLES',
  ETC = 'ETC',
}
