import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/header/header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="en">
      <body className="flex min-h-screen flex-col px-[60px] antialiased">
        <Header />
        {children}
      </body>
    </html>
  )
}

export default RootLayout
